/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class VariaveisFase1 extends javax.swing.JFrame {

    String movimento1 = "";
    String movimento2 = "";
    String movimento3 = "";
    String movimento4 = "";
    
    public VariaveisFase1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapa = new javax.swing.JLabel();
        Movimento4 = new javax.swing.JTextField();
        Movimento3 = new javax.swing.JTextField();
        Movimento2 = new javax.swing.JTextField();
        Movimento1 = new javax.swing.JTextField();
        ButtonEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(881, 624));
        setMinimumSize(new java.awt.Dimension(881, 624));
        setPreferredSize(new java.awt.Dimension(881, 624));
        setResizable(false);
        getContentPane().setLayout(null);

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/variaveis/fase 1/1.png"))); // NOI18N
        mapa.setText("mapa");
        getContentPane().add(mapa);
        mapa.setBounds(30, 110, 510, 460);
        getContentPane().add(Movimento4);
        Movimento4.setBounds(630, 370, 210, 30);
        getContentPane().add(Movimento3);
        Movimento3.setBounds(630, 330, 210, 30);

        Movimento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Movimento2ActionPerformed(evt);
            }
        });
        getContentPane().add(Movimento2);
        Movimento2.setBounds(630, 290, 210, 30);

        Movimento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Movimento1ActionPerformed(evt);
            }
        });
        getContentPane().add(Movimento1);
        Movimento1.setBounds(630, 250, 210, 30);

        ButtonEnviar.setText("ENVIAR");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEnviar);
        ButtonEnviar.setBounds(730, 510, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 11 (2).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed

     if (!Movimento1.getText().equals("String move = ‘rigth’;")){
        JOptionPane.showMessageDialog(null, "Movimento errado!!!");
     }else if (!Movimento2.getText().equals("String move = ‘down’;")){
        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/variaveis/fase 1/2.png")));
        JOptionPane.showMessageDialog(null, "Movimento errado!!!");
     }else if (!Movimento3.getText().equals("String move = ‘left’;")){
        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/variaveis/fase 1/3.png")));
        JOptionPane.showMessageDialog(null, "Movimento errado!!!");
     }else if (!Movimento4.getText().equals("String move = ‘down’;")){
        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/variaveis/fase 1/4.png")));
        JOptionPane.showMessageDialog(null, "Movimento errado!!!");
     }

       if (Movimento1.getText().equals("String move = ‘rigth’;") && (Movimento2.getText().equals("String move = ‘down’;") && (Movimento3.getText().equals("String move = ‘left’;") && (Movimento4.getText().equals("String move = ‘down’;"))))){                  
        JOptionPane.showMessageDialog(null, "Parabéns você chegou ao tesouro!!!");   
        Variaveis2 v2 = new Variaveis2();
        v2.setVisible(true);
        dispose();
       }
        
    }//GEN-LAST:event_ButtonEnviarActionPerformed

    private void Movimento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Movimento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Movimento1ActionPerformed

    private void Movimento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Movimento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Movimento2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VariaveisFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VariaveisFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VariaveisFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VariaveisFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VariaveisFase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JTextField Movimento1;
    private javax.swing.JTextField Movimento2;
    private javax.swing.JTextField Movimento3;
    private javax.swing.JTextField Movimento4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mapa;
    // End of variables declaration//GEN-END:variables
}
